# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abaac5e8aa566c8de9426ac51a2cc4550c7076cbfabe148987ec8935bc130397305382c4e59ba4595f5a5a3d80c6f722d30f3cc1999dca15297027e849e4cb0c

test:
  secret_key_base: ef30a216003476a40eef1a540cc80674d9ea5424888f3b1b7c13eba29bc911ce9dcf184b2815fdcc6e7577766d54dc0372b2d4ddc3262a229bd2310c32d9c312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
